name: Build package


on:
  workflow_call:
    inputs:
      runner:
        type: string
        required: true
      package:
        type: string
        required: true
      tag:
        type: boolean
        required: false
        default: false
    secrets:
      cachix-token:
        required: true

jobs:
  build:
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Increase swap
        run: |
          SWAPFILE=/newswapfile
          sudo fallocate -l 30G $SWAPFILE
          sudo chmod 600 $SWAPFILE
          sudo mkswap $SWAPFILE
          sudo swapon $SWAPFILE
      - name: Disable apparmor unprivileged user namespace restriction
        run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
      - uses: actions/checkout@v7
        with:
          ref: main
      - uses: ./.github/actions/build+cache
        with:
          package: "${{ inputs.package }}"
          cachix-token: '${{ secrets.cachix-token }}'
          pin: true
      - name: Weekly Tagging
        if: inputs.tag
        run: |
          if [[ "$(date +'%w')" == "1" ]]; then
            echo "Tagging current commit as weekly"
            git tag weekly
            git push origin weekly
          fi
