name: Watch nixpkgs updates

on:
    schedule:
        - cron: '17 * * * *'
    workflow_dispatch:

permissions:
  contents: write

jobs:
    watch-for-updates:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v7
          - name: Check for nixpkgs updates
            id: update
            uses: ./.github/actions/flake-update
            with:
              inputs: "nixpkgs"
          - run: gh workflow run nightly.yaml --ref main
            if: steps.update.outputs.changed == 'true'
            env:
              GH_TOKEN: ${{ secrets.GH_PAT }}
